--- #install webserver using variable
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes
  vars:
          pkgname: httpd
  tasks:
          - name: INSTALL WEB SERVER ON ANSIBLE CLIENTS.
            action: yum name='{{pkgname}}' state=installed
            action: service name='{{pkgname}}' state=restarted
